[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.31"
eframe = { version = "0.31", default-features = false, features = [
    "default_fonts",
    "glow",
    "persistence",
    "wayland",
] }
log = "0.4"
serde = { version = "1.0.217", features = ["derive"] }
wasm-bindgen-futures = "0.4.50"

[profile.release]
opt-level = 2